### ISSUE TITLE
Bugfix on callback

### ISSUE THREAD

**Issue by thesunny** [dominictarr/exif-orientation-lite#1]
Hi @dominictarr 

Thanks for making this tiny library available. It's exactly what I needed to get the exif orientation data only.

I just noticed a little bug that likely happened when you were converting this library from being asynchronous to synchronous.

```js
      if (view.getUint32(offset += 2, false) !== 0x45786966) return callback(-1)
```

Since there is no callback function, this code path throws an error.

It should probably be:

```js
      if (view.getUint32(offset += 2, false) !== 0x45786966) return -1
```

I could submit a pull request but this seems so small that its probably just as easy for you to just do it.

**Comment by dominictarr** [comment]
thanks, fixed in 1.0.1
